<?php

namespace Congreso\CongresoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloRepository extends EntityRepository
{
	public function getLatestArticulos($limit = null)
{
	$qp = $this->createQueryBuilder('p')->select('p')->addOrderBy('p.publicacion', 'DESC');

	if (false === is_null($limit))
		$qp->setMaxResults($limit);

	return $qp->getQuery()->getResult();
}
}
