<?php

namespace Congreso\CongresoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CientificoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CientificoRepository extends EntityRepository
{
}
