<?php

namespace Congreso\CongresoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
		public function getCommentsForArticulo($articuloId, $approved = true)
{
	$qp = $this->createQueryBuilder('c')->select('c')->where('c.articulo = :articulo_id')->addOrderBy('c.created')->setParameter('articulo_id', $articuloId);

	if (false === is_null($approved))
		$qp->andWhere('c.approved = :approved')->setParameter('approved', $approved);

	return $qp->getQuery()->getResult();
}
}
